//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BuildingMonitorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuildingMonitorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.BuildingMonitorResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Contracts.
        /// </summary>
        internal static string AdminContract {
            get {
                return ResourceManager.GetString("AdminContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Contract.
        /// </summary>
        internal static string AdminContractAdd {
            get {
                return ResourceManager.GetString("AdminContractAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Contract.
        /// </summary>
        internal static string AdminContractEdit {
            get {
                return ResourceManager.GetString("AdminContractEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Contractors.
        /// </summary>
        internal static string AdminContractor {
            get {
                return ResourceManager.GetString("AdminContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Contractor.
        /// </summary>
        internal static string AdminContractorAdd {
            get {
                return ResourceManager.GetString("AdminContractorAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Monitor Manager.
        /// </summary>
        internal static string BuildingMonitorManagerHeading {
            get {
                return ResourceManager.GetString("BuildingMonitorManagerHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ContractAddSubItem {
            get {
                return ResourceManager.GetString("ContractAddSubItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from Project to SubItem.
        /// </summary>
        internal static string ContractEditSelectNavigator {
            get {
                return ResourceManager.GetString("ContractEditSelectNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string ContractFieldAmount {
            get {
                return ResourceManager.GetString("ContractFieldAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        internal static string ContractFieldContractor {
            get {
                return ResourceManager.GetString("ContractFieldContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string ContractFieldCreatedBy {
            get {
                return ResourceManager.GetString("ContractFieldCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        internal static string ContractFieldCreatedOn {
            get {
                return ResourceManager.GetString("ContractFieldCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string ContractFieldCurrency {
            get {
                return ResourceManager.GetString("ContractFieldCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate.
        /// </summary>
        internal static string ContractFieldCurrencyRate {
            get {
                return ResourceManager.GetString("ContractFieldCurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date End.
        /// </summary>
        internal static string ContractFieldDateEnd {
            get {
                return ResourceManager.GetString("ContractFieldDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Start.
        /// </summary>
        internal static string ContractFieldDateStart {
            get {
                return ResourceManager.GetString("ContractFieldDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted By.
        /// </summary>
        internal static string ContractFieldDeletedBy {
            get {
                return ResourceManager.GetString("ContractFieldDeletedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted On.
        /// </summary>
        internal static string ContractFieldDeletedOn {
            get {
                return ResourceManager.GetString("ContractFieldDeletedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ContractFieldDescription {
            get {
                return ResourceManager.GetString("ContractFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        internal static string ContractFieldId {
            get {
                return ResourceManager.GetString("ContractFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Paid Work?.
        /// </summary>
        internal static string ContractFieldIsPaidWork {
            get {
                return ResourceManager.GetString("ContractFieldIsPaidWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        internal static string ContractFieldModifiedBy {
            get {
                return ResourceManager.GetString("ContractFieldModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        internal static string ContractFieldModifiedOn {
            get {
                return ResourceManager.GetString("ContractFieldModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        internal static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string ContractorBank {
            get {
                return ResourceManager.GetString("ContractorBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        internal static string ContractorBankAccount {
            get {
                return ResourceManager.GetString("ContractorBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movile.
        /// </summary>
        internal static string ContractorMovileLabel {
            get {
                return ResourceManager.GetString("ContractorMovileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ContractorNameLabel {
            get {
                return ResourceManager.GetString("ContractorNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string ContractorPhoneLabel {
            get {
                return ResourceManager.GetString("ContractorPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialties.
        /// </summary>
        internal static string ContractorSpecialtiesLabel {
            get {
                return ResourceManager.GetString("ContractorSpecialtiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ContractorStatusLabel {
            get {
                return ResourceManager.GetString("ContractorStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Required.
        /// </summary>
        internal static string ContractProgressRequired {
            get {
                return ResourceManager.GetString("ContractProgressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string LabelBlock {
            get {
                return ResourceManager.GetString("LabelBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string LabelCash {
            get {
                return ResourceManager.GetString("LabelCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string LabelCheck {
            get {
                return ResourceManager.GetString("LabelCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string LabelData {
            get {
                return ResourceManager.GetString("LabelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string LabelDetail {
            get {
                return ResourceManager.GetString("LabelDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string LabelEdit {
            get {
                return ResourceManager.GetString("LabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LabelFieldPrefix {
            get {
                return ResourceManager.GetString("LabelFieldPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string LabelFieldSuffix {
            get {
                return ResourceManager.GetString("LabelFieldSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available data to display.
        /// </summary>
        internal static string LabelGridEmpty {
            get {
                return ResourceManager.GetString("LabelGridEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string LabelGroup {
            get {
                return ResourceManager.GetString("LabelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string LabelItem {
            get {
                return ResourceManager.GetString("LabelItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string LabelMore {
            get {
                return ResourceManager.GetString("LabelMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string LabelPay {
            get {
                return ResourceManager.GetString("LabelPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string LabelPrint {
            get {
                return ResourceManager.GetString("LabelPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string LabelProject {
            get {
                return ResourceManager.GetString("LabelProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string LabelQuantity {
            get {
                return ResourceManager.GetString("LabelQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string LabelRemove {
            get {
                return ResourceManager.GetString("LabelRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubItem.
        /// </summary>
        internal static string LabelSubItem {
            get {
                return ResourceManager.GetString("LabelSubItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string LabelTipRequired {
            get {
                return ResourceManager.GetString("LabelTipRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string LabelUnit {
            get {
                return ResourceManager.GetString("LabelUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        internal static string LabelWork {
            get {
                return ResourceManager.GetString("LabelWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Empty -.
        /// </summary>
        internal static string OptionEmpty {
            get {
                return ResourceManager.GetString("OptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select -.
        /// </summary>
        internal static string OptionSelect {
            get {
                return ResourceManager.GetString("OptionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Work.
        /// </summary>
        internal static string PaidWork {
            get {
                return ResourceManager.GetString("PaidWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        internal static string PaidWorkAdvance {
            get {
                return ResourceManager.GetString("PaidWorkAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check number.
        /// </summary>
        internal static string PaymentCheckNumber {
            get {
                return ResourceManager.GetString("PaymentCheckNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid to.
        /// </summary>
        internal static string PaymentPaidToContractor {
            get {
                return ResourceManager.GetString("PaymentPaidToContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay from:.
        /// </summary>
        internal static string PaymentPayFrom {
            get {
                return ResourceManager.GetString("PaymentPayFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay to:.
        /// </summary>
        internal static string PaymentPayTo {
            get {
                return ResourceManager.GetString("PaymentPayTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Recording.
        /// </summary>
        internal static string ProgressRec {
            get {
                return ResourceManager.GetString("ProgressRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Progress Recording.
        /// </summary>
        internal static string ProgressRecAdd {
            get {
                return ResourceManager.GetString("ProgressRecAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current progress is required..
        /// </summary>
        internal static string ProgressRecErrorCurrentReq {
            get {
                return ResourceManager.GetString("ProgressRecErrorCurrentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current progress must be greater than Initial one..
        /// </summary>
        internal static string ProgressRecErrorInitialGreatherThanCurrent {
            get {
                return ResourceManager.GetString("ProgressRecErrorInitialGreatherThanCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial progress is required..
        /// </summary>
        internal static string ProgressRecErrorInitialReq {
            get {
                return ResourceManager.GetString("ProgressRecErrorInitialReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data..
        /// </summary>
        internal static string ProgressRecErrorInvalid {
            get {
                return ResourceManager.GetString("ProgressRecErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress must be between 0 and 100..
        /// </summary>
        internal static string ProgressRecErrorOutOfRange {
            get {
                return ResourceManager.GetString("ProgressRecErrorOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Progress.
        /// </summary>
        internal static string ProgressRecFieldCurrent {
            get {
                return ResourceManager.GetString("ProgressRecFieldCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ProgressRecFieldDate {
            get {
                return ResourceManager.GetString("ProgressRecFieldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Progress.
        /// </summary>
        internal static string ProgressRecFieldInitial {
            get {
                return ResourceManager.GetString("ProgressRecFieldInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Progress.
        /// </summary>
        internal static string ProgressRecLastProgress {
            get {
                return ResourceManager.GetString("ProgressRecLastProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Progress.
        /// </summary>
        internal static string ProgressRecNewProgress {
            get {
                return ResourceManager.GetString("ProgressRecNewProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress recording saved sucessfully..
        /// </summary>
        internal static string ProgressRecSuccessAdd {
            get {
                return ResourceManager.GetString("ProgressRecSuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;rarr;.
        /// </summary>
        internal static string SeparatorLR {
            get {
                return ResourceManager.GetString("SeparatorLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialties.
        /// </summary>
        internal static string Specialties {
            get {
                return ResourceManager.GetString("Specialties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialty.
        /// </summary>
        internal static string Specialty {
            get {
                return ResourceManager.GetString("Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Success!.
        /// </summary>
        internal static string TitlePaymentSuccess {
            get {
                return ResourceManager.GetString("TitlePaymentSuccess", resourceCulture);
            }
        }
    }
}
